### ISSUE TITLE
Am not sure how to use this, erm, mod....

### ISSUE THREAD

**Issue by Brickticks** [DrexHD/MC-270325#1]
Hello Mr. Drex,
Small issue, I've never used a mod before, and am thus not sure how to use this one to save my poor books.  Also, once I use it, and get my world updated to whatever pre-release is most recent at the time off using it, how and can I remove the mod and return things to normal?  Also, what will happen when I do remove the mod?  Is that even possible?  Please, I need some clarification on this issue, hopefully so I can keep using minecraft and not be stuck on snapshot 24w12a forever.  Thanks, and have a great day.
Rockatoa, Brickticks out!

**Comment by DrexHD** [comment]
## Please make sure to create a backup of your world before doing any of this!!!

This is a [fabric](https://fabricmc.net/) mod. There are plenty of tutorials on the web that explain how to install fabric mods. To use this mod install it on your client (or server if you want to fix a server world) on 24w14a or later and join your world. This mod adds a datafixer that properly fixes books to the game, you need to have the mod installed as long as there is still data from affected versions in your world. You can click "Optimize World" to update all your *world* data, to update your player data enter the world. Once world data and player data is updated you can safely remove the mod and launch your world without it. If you are running a server you will need to keep this mod installed "forever", because there is no way to upgrade all player data (players need to join).

**Comment by Brickticks** [comment]
Oh, thank you, this should work great...  Erm, one thing though, which file is it I need to download from the list here on Github?  Just want to be absolutely sure I get the right one.

**Comment by DrexHD** [comment]
You need `mc-270325-1.1.0.jar`. I have created a [github release](https://github.com/DrexHD/MC-270325/releases/tag/v1.1.0) that contains that jar.

**Comment by Brickticks** [comment]
Tried it, it didn't work, my books still erased.  What did I do wrong?  I created a mods folder in .minecraft, added the .jar file to said mods folder, and nothing happened.  The books still erased.  Hmm, what did I do wrong?  I mean, I'm running 1.20.5 pre-release 1, does that make a difference?  Are there separate files for different version installations?  Still kinda need help, thank you for your patience.

**Comment by DrexHD** [comment]
Doesn't sound like you [installed fabric](https://fabricmc.net/use/installer/). The mods folder should be created by fabric on first startup!

**Comment by Brickticks** [comment]
OK, am back from the dentist, that was awful.  Nonetheless, I've tried installing fabric, as per the link you provided, I've downloaded the fabric API and your mod, per the links provided, I got the mods folder to exist, easy enough.  Problem, it doesn't seem to have worked.  I looked up the video on how to install fabric mods, via google to the fabric wiki and then a link from the fabric wiki, and when I go to launch the game, everything seems normal, except the "mods" button seen in the video doesn't seem to appear.  So, what did I do wrong this time?  Should I try to open my world?  I clicked on the correct fabric API for 1.20.5 pre-release 1, but it doesn't seem to have worked....  I'll wait on a response from you, since I can't really think of what else to do.

**Comment by Brickticks** [comment]
OK, I think I figured out what I did wrong, but uh, how do I remove fabric, the fabric api, and modmenu when I'm done with them?  I'd assume just delete the files in question, but want to make sure that will work....  AM going to go get modmenu, and then will check back in....  hopefully this works.

**Comment by Brickticks** [comment]
OK, got it working, books saved.  Now then, how the heck do I get rid of fabric?  I have no continued need for it, so how should I get rid of it?  Guess I'll just try the old fashioned way....

**Comment by Brickticks** [comment]
And all is right with the world!  YAY!!!!!
